version: '3.7'
volumes:
  postgres_data:


services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  admin_panel:
    container_name: admin_panel
#    image: admin_panel:latest
    build: .
#      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    container_name: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static_volume:/code/static

    ports:
      - "8000:8000"
    depends_on:
      - admin_panel