FROM python:3.7.4

WORKDIR /code

RUN mkdir -p movies_admin/requirements

COPY movies_admin/requirements/*.txt movies_admin/requirements/

RUN pip install -r movies_admin/requirements/dev.txt

COPY . .

CMD gunicorn wsgi:application --bind 0.0.0.0:8000